[project]
name = "editor-yt"
version = "0.1.0"
description = ""
main_script = "./src/main.py"

[packages]
PyQt5 = "5.15.7"
QScintilla = "2.13.3"
jedi = "0.18.1"

[scripts]
build-qrc = "pyrcc5 ./src/icons/resouces.qrc -o ./src/resources.py"
upgrade-pip = "python -m pip install --upgrade pip"
